project_name: circlepipe
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: circlepipe
    ldflags:
      - -s -w -X github.com/ThoughtWorks-DPS/circlepipe/cmd.Version={{.Version}}
signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PWD }}'
    args: ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all
archives:
  - name_template: >-
      {{- .ProjectName }}_{{- title .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
