repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: forbid-new-submodules
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
      - id: git-secrets
        name: git-secrets
        entry: git-secrets
        language: system
        args: ["--scan"]
  - repo: local
    hooks:
      - id: staticcheck
        name: staticcheck
        entry: staticcheck ./...
        types: [go]
        language: golang
        pass_filenames: false
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --fix
        types: [go]
        language: golang
        pass_filenames: false
